language: node_js

node_js: "6.1"

services:
  - mongodb
  - postgresql
postgres:
  adapter: postgresql
  database: myapp_test
  username: postgres
before_script:
  - psql -c 'create database psp;' -U postgres
notifications:
  slack: '4yopping:ALhrivGHquJzo5MPODfnRIvI'
script: npm test
addons:
  postgresql: "9.4"
